openjij: openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType > Class Template Reference
openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType > Class Template Reference
#include <integer_polynomial_sa_system.hpp>
Public Member Functions
IntegerSASystem (const graph::IntegerPolynomialModel &model, const typename RandType::result_type seed)
double CalculateEnergy (const std::vector< utility::IntegerVariable > &state) const
std::int64_t GenerateCandidateValue (std::int64_t index)
double GetEnergyDifference (std::int64_t index, std::int64_t new_value) const
void SetValue (std::int64_t index, std::int64_t new_value)
std::pair< int, double > GetMinEnergyDifference (std::int64_t index)
double GetLinearCoeff (std::int64_t index) const
const std::vector< utility::IntegerVariable > & GetState () const
double GetEnergy () const
bool OnlyMultiLinearCoeff (std::int64_t index) const
bool UnderQuadraticCoeff (std::int64_t index) const
Public Attributes
const graph::IntegerPolynomialModel & model
const RandType::result_type seed
RandType random_number_engine
Private Attributes
std::vector< utility::IntegerVariable > state_
double energy_
std::vector< int > zero_count_
std::vector< double > term_prod_
std::vector< std::unordered_map< std::int64_t, double > > base_energy_difference_
Constructor & Destructor Documentation
IntegerSASystem()
template<typename RandType > openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::IntegerSASystem (const graph::IntegerPolynomialModel & model, const typename RandType::result_type seed) inline
References openjij::graph::IntegerPolynomialModel::GetBounds(), openjij::graph::IntegerPolynomialModel::GetKeyValueList(), and openjij::graph::IntegerPolynomialModel::GetNumVariables().
Member Function Documentation
CalculateEnergy()
template<typename RandType > double openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::CalculateEnergy (const std::vector< utility::IntegerVariable > & state) const inline
GenerateCandidateValue()
template<typename RandType > std::int64_t openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::GenerateCandidateValue (std::int64_t index) inline
GetEnergy()
template<typename RandType > double openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::GetEnergy () const inline
GetEnergyDifference()
template<typename RandType > double openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::GetEnergyDifference (std::int64_t index, std::int64_t new_value) const inline
GetLinearCoeff()
template<typename RandType > double openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::GetLinearCoeff (std::int64_t index) const inline
GetMinEnergyDifference()
template<typename RandType > std::pair< int, double > openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::GetMinEnergyDifference (std::int64_t index) inline
GetState()
template<typename RandType > const std::vector< utility::IntegerVariable > & openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::GetState () const inline
OnlyMultiLinearCoeff()
template<typename RandType > bool openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::OnlyMultiLinearCoeff (std::int64_t index) const inline
SetValue()
template<typename RandType > void openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::SetValue (std::int64_t index, std::int64_t new_value) inline
UnderQuadraticCoeff()
template<typename RandType > bool openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::UnderQuadraticCoeff (std::int64_t index) const inline
Member Data Documentation
base_energy_difference_
template<typename RandType > std::vector<std::unordered_map<std::int64_t, double> > openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::base_energy_difference_ private
energy_
template<typename RandType > double openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::energy_ private
model
template<typename RandType > const graph::IntegerPolynomialModel& openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::model
random_number_engine
template<typename RandType > RandType openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::random_number_engine
seed
template<typename RandType > const RandType::result_type openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::seed
state_
template<typename RandType > std::vector<utility::IntegerVariable> openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::state_ private
term_prod_
template<typename RandType > std::vector<double> openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::term_prod_ private
zero_count_
template<typename RandType > std::vector<int> openjij::system::IntegerSASystem< graph::IntegerPolynomialModel, RandType >::zero_count_ private
The documentation for this class was generated from the following file:
integer_polynomial_sa_system.hpp