openjij: openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType > Class Template Reference
openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType > Class Template Reference
#include <integer_quadratic_sa_system.hpp>
Public Member Functions
IntegerSASystem (const graph::IntegerQuadraticModel &model, const typename RandType::result_type seed)
double CalculateEnergy (const std::vector< utility::IntegerVariable > &state) const
std::int64_t GenerateCandidateValue (std::int64_t index)
double GetEnergyDifference (std::int64_t index, std::int64_t new_value) const
void SetValue (std::int64_t index, std::int64_t new_value)
std::pair< int, double > GetMinEnergyDifference (std::int64_t index)
const std::vector< utility::IntegerVariable > & GetState () const
const std::vector< double > & GetLinearCoeff () const
const std::vector< double > & GetQuadCoeff () const
double GetEnergy () const
bool OnlyMultiLinearCoeff (std::int64_t index) const
bool UnderQuadraticCoeff (std::int64_t index) const
double GetLinearCoeff (std::int64_t index) const
Public Attributes
const graph::IntegerQuadraticModel model
const std::int64_t seed
RandType random_number_engine
Private Attributes
std::vector< utility::IntegerVariable > state_
double energy_
std::vector< double > quad_coeff_
std::vector< double > linear_coeff_
Constructor & Destructor Documentation
IntegerSASystem()
template<typename RandType > openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::IntegerSASystem (const graph::IntegerQuadraticModel & model, const typename RandType::result_type seed) inline
References openjij::graph::IntegerQuadraticModel::GetBounds(), openjij::graph::IntegerQuadraticModel::GetLinear(), openjij::graph::IntegerQuadraticModel::GetNumVariables(), openjij::graph::IntegerQuadraticModel::GetQuadratic(), and openjij::graph::IntegerQuadraticModel::GetSquared().
Member Function Documentation
CalculateEnergy()
template<typename RandType > double openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::CalculateEnergy (const std::vector< utility::IntegerVariable > & state) const inline
GenerateCandidateValue()
template<typename RandType > std::int64_t openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::GenerateCandidateValue (std::int64_t index) inline
GetEnergy()
template<typename RandType > double openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::GetEnergy () const inline
GetEnergyDifference()
template<typename RandType > double openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::GetEnergyDifference (std::int64_t index, std::int64_t new_value) const inline
GetLinearCoeff() [1/2]
template<typename RandType > const std::vector< double > & openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::GetLinearCoeff () const inline
GetLinearCoeff() [2/2]
template<typename RandType > double openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::GetLinearCoeff (std::int64_t index) const inline
GetMinEnergyDifference()
template<typename RandType > std::pair< int, double > openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::GetMinEnergyDifference (std::int64_t index) inline
GetQuadCoeff()
template<typename RandType > const std::vector< double > & openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::GetQuadCoeff () const inline
GetState()
template<typename RandType > const std::vector< utility::IntegerVariable > & openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::GetState () const inline
OnlyMultiLinearCoeff()
template<typename RandType > bool openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::OnlyMultiLinearCoeff (std::int64_t index) const inline
SetValue()
template<typename RandType > void openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::SetValue (std::int64_t index, std::int64_t new_value) inline
UnderQuadraticCoeff()
template<typename RandType > bool openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::UnderQuadraticCoeff (std::int64_t index) const inline
Member Data Documentation
energy_
template<typename RandType > double openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::energy_ private
linear_coeff_
template<typename RandType > std::vector<double> openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::linear_coeff_ private
model
template<typename RandType > const graph::IntegerQuadraticModel openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::model
quad_coeff_
template<typename RandType > std::vector<double> openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::quad_coeff_ private
random_number_engine
template<typename RandType > RandType openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::random_number_engine
seed
template<typename RandType > const std::int64_t openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::seed
state_
template<typename RandType > std::vector<utility::IntegerVariable> openjij::system::IntegerSASystem< graph::IntegerQuadraticModel, RandType >::state_ private
The documentation for this class was generated from the following file:
integer_quadratic_sa_system.hpp