openjij: openjij::sampler Namespace Reference
openjij::sampler Namespace Reference
Namespaces
namespace base_sa_sample_hubo
namespace csqa_sampler
namespace response
namespace sa_sampler
namespace sampler
namespace sqa_sampler
Classes
struct IntegerSAResult
class SASampler
Class for executing simulated annealing.
Functions
template<class ModelType , class RandType , class StateUpdater >
IntegerSAResult BaseSA (const ModelType &model, const utility::TemperatureSchedule schedule, const std::int64_t num_sweeps, const typename RandType::result_type seed, const double min_T, const double max_T, const bool log_history)
template<class ModelType , class UpdaterType >
IntegerSAResult SolveByIntegerSAImpl (const ModelType &model, const std::int64_t num_sweeps, const algorithm::RandomNumberEngine rand_type, const utility::TemperatureSchedule schedule, const std::int64_t seed, const double min_T, const double max_T, const bool log_history)
template<class ModelType >
IntegerSAResult SolveByIntegerSA (const ModelType &model, const std::int64_t num_sweeps, const algorithm::UpdateMethod update_method, const algorithm::RandomNumberEngine rand_type, const utility::TemperatureSchedule schedule, const std::int64_t seed, const double min_T, const double max_T, const bool log_history)
template<class ModelType >
std::vector< IntegerSAResult > SampleByIntegerSA (const ModelType &model, const std::int64_t num_sweeps, const algorithm::UpdateMethod update_method, const algorithm::RandomNumberEngine rand_type, const utility::TemperatureSchedule schedule, const std::int64_t num_reads, const std::int64_t seed, const std::int32_t num_threads, const double min_T, const double max_T, const bool log_history)
template<class ModelType >
auto make_sa_sampler (const ModelType &model)
Variables
__path__ = extend_path(__path__, __name__)
list __all__
Function Documentation
BaseSA()
template<class ModelType , class RandType , class StateUpdater > IntegerSAResult openjij::sampler::BaseSA (const ModelType & model, const utility::TemperatureSchedule schedule, const std::int64_t num_sweeps, const typename RandType::result_type seed, const double min_T, const double max_T, const bool log_history)
References openjij::sampler::IntegerSAResult::energy, openjij::sampler::IntegerSAResult::energy_history, openjij::utility::GEOMETRIC, openjij::utility::LINEAR, openjij::sampler::IntegerSAResult::solution, and openjij::sampler::IntegerSAResult::temperature_history.
make_sa_sampler()
template<class ModelType > auto openjij::sampler::make_sa_sampler (const ModelType & model)
References make_sa_sampler().
Referenced by make_sa_sampler().
SampleByIntegerSA()
template<class ModelType > std::vector< IntegerSAResult > openjij::sampler::SampleByIntegerSA (const ModelType & model, const std::int64_t num_sweeps, const algorithm::UpdateMethod update_method, const algorithm::RandomNumberEngine rand_type, const utility::TemperatureSchedule schedule, const std::int64_t num_reads, const std::int64_t seed, const std::int32_t num_threads, const double min_T, const double max_T, const bool log_history)
References SolveByIntegerSA().
SolveByIntegerSA()
template<class ModelType > IntegerSAResult openjij::sampler::SolveByIntegerSA (const ModelType & model, const std::int64_t num_sweeps, const algorithm::UpdateMethod update_method, const algorithm::RandomNumberEngine rand_type, const utility::TemperatureSchedule schedule, const std::int64_t seed, const double min_T, const double max_T, const bool log_history)
References openjij::algorithm::HEAT_BATH, openjij::algorithm::METROPOLIS, openjij::algorithm::OPT_METROPOLIS, and openjij::algorithm::SUWA_TODO.
Referenced by SampleByIntegerSA().
SolveByIntegerSAImpl()
template<class ModelType , class UpdaterType > IntegerSAResult openjij::sampler::SolveByIntegerSAImpl (const ModelType & model, const std::int64_t num_sweeps, const algorithm::RandomNumberEngine rand_type, const utility::TemperatureSchedule schedule, const std::int64_t seed, const double min_T, const double max_T, const bool log_history)
References openjij::algorithm::MT, openjij::algorithm::MT_64, and openjij::algorithm::XORSHIFT.
Variable Documentation
__all__
list openjij.sampler.__all__ private
Initial value:
=  [
    "CSQASampler",
    "Response",
    "SASampler",
    "measure_time",
    "SQASampler",
]
__path__
openjij.sampler.__path__ = extend_path(__path__, __name__) private