openjij: openjij::updater::HeatBathUpdater Struct Reference
openjij::updater::HeatBathUpdater Struct Reference
#include <single_integer_move.hpp>
Public Member Functions
template<typename SystemType >
std::int64_t GenerateNewValue (SystemType &sa_system, const std::int64_t index, const double T, const double _progress)
template<typename SystemType >
std::int64_t ForAll (SystemType &sa_system, const std::int64_t index, const double T, const double _progress)
template<typename SystemType >
std::int64_t ForBilinear (SystemType &sa_system, const std::int64_t index, const double T, const double _progress)
Public Attributes
std::uniform_real_distribution< double > dist {0.0, 1.0}
Member Function Documentation
ForAll()
template<typename SystemType > std::int64_t openjij::updater::HeatBathUpdater::ForAll (SystemType & sa_system, const std::int64_t index, const double T, const double _progress) inline
References dist.
Referenced by GenerateNewValue().
ForBilinear()
template<typename SystemType > std::int64_t openjij::updater::HeatBathUpdater::ForBilinear (SystemType & sa_system, const std::int64_t index, const double T, const double _progress) inline
References dist.
Referenced by GenerateNewValue().
GenerateNewValue()
template<typename SystemType > std::int64_t openjij::updater::HeatBathUpdater::GenerateNewValue (SystemType & sa_system, const std::int64_t index, const double T, const double _progress) inline
References ForAll(), and ForBilinear().
Member Data Documentation
dist
std::uniform_real_distribution<double> openjij::updater::HeatBathUpdater::dist {0.0, 1.0}
Referenced by ForAll(), and ForBilinear().
The documentation for this struct was generated from the following file:
single_integer_move.hpp